### ISSUE TITLE
Task #2

### ISSUE THREAD

**Issue by lexastef** [GlebKast/PhotoFlow#1]
- Guest shouldn't have access to edit and remove buttons (main page)
- Footer should contain all data defined by TP (date, group)
- (minor) Mockup parts should be obvious (@author, description, title etc.)
- Add/Edit mode should contain a tags
- Add/Edit mode should show current date.
- (Critical) Edit mode should have image picker.
- (Critical) User/Guest have no filter functionality
- Error page (for errors caused by system)

Mark: 6 (+1 prototype system (obvious action behaviour))

**Comment by GlebKast** [comment]
- like, edit and remove buttons are unclickable for guest (or I should show this buttoms only for registered user?)
- all other mistakes are connected with TP which I haven't seen. Now I've found the link to TP, but there are no links to TP on the "Задание 2" page...
