### ISSUE TITLE
Taks #4

### ISSUE THREAD

**Issue by alexey-kozlenkov** [GlebKast/PhotoFlow#2]
1. In `getPhotoPosts` calling sort on a variable that is a reference copy (`sortPostsByDate(res);`) of the origin array will modify origin array. 
2. In `getPhotoPosts` all filter data should be in `filterConfig`
3. Filtering by date is invalid, you leave only elements with the same month. (why?)
4. In `getPostById` returning 1 in case post has not been found seems strange.
5. In `editPost` clone ` var clone = getPostById(postID);` references to the same object in memory so when you later modify `clone`, you also modify origin object.

**Comment by GlebKast** [comment]
I've fixed this bugs. Thank you
